### PR TITLE
Return unmodified message if no types match

### PR DESCRIPTION
**Pull request by owenh000**
When the seek_target() function does not find a match, the unmodified
message should be printed to standard out.

### CODE REVIEW

**Comment by oblitum** [comment]
Good catch! Thanks 👌

**Comment by owenh000** [comment]
I discovered this while using mutt's "bounce" command. Bounced messages should not be modified. I would like to use the following to make the bounce command work properly, but it doesn't work.

```
macro   index,pager b       \
"<enter-command> set my_sendmail=\$sendmail<enter>\
<enter-command> set sendmail=msmtp<enter>\
<bounce-message>\
<enter-command> set sendmail=\$my_sendmail<enter>" \
"remail a message to another user"
```

It is unfortunate that `send-hook` cannot be used to modify a message before sending, then MIMEmbellish could be used in that way instead. This would have the added benefit of saving via Fcc the  actual modified message that was sent (because sometimes I might need to see what the HTML was that I actually sent).

Thanks for the useful script!

**Comment by oblitum** [comment]
I've never gone to that level of mutt macro magic, and can't barely understand what you're trying to do 🤔, but the neomutt devs are generally quite welcoming of suggestion. Maybe it's an opportunity for feature request. Their IRC channel is quite active.

**Comment by owenh000** [comment]
The idea is to save the currently defined `$sendmail` in a separate variable, modify it to bypass MIMEmbellish, do the bounce, then set it back to what it was before.

I'll look into making a suggestion for NeoMutt.

**Pull request merged**
